[package]
name = "modules"
version.workspace = true
edition.workspace = true

[dependencies]
abi = { workspace = true }
borsh = { workspace = true }
guest = { workspace = true }

[dev-dependencies]
commonware-cryptography = { workspace = true }
commonware-runtime = { workspace = true }
fixture-probe = { workspace = true }
host = { workspace = true }
keyscheme = { workspace = true, features = ["testkit"] }
tempfile = { workspace = true }
