[package]
name = "forge"
edition.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gitcore = { workspace = true }
abi = { workspace = true }
guest = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chat = { path = "../chat" }
