[workspace]
resolver = "2"
members = [
    "module-registry",
    "valset",
    "identity",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
abi = { path = "../../sdk/abi" }
guest = { path = "../../sdk/guest" }
modules = { path = ".." }
borsh = { version = "1", default-features = false, features = ["derive", "std"] }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1
